/*
 * PulseOximeterHandleNames.h
 *
 *  Created on: Jan 16, 2019
 *      Author: rosenau
 */

#ifndef CTESTCASES_TOOLS_PULSEOXIMETERHANDLENAMES_H_
#define CTESTCASES_TOOLS_PULSEOXIMETERHANDLENAMES_H_

const std::string PULSE_OXIMETER_MDS_HANDLE("MDC_DEV_PULS_OXIM_MDS");
const std::string PULSE_OXIMETER_VMD_HANDLE("MDC_DEV_PULS_OXIM_VMD");
const std::string PULSE_OXIMETER_PULS_CHAN_HANDLE("MDC_DEV_PULS_OXIM_PULS_CHAN");
const std::string PULSE_OXIMETER_PULS_SAT_O2_CHAN_HANDLE("MDC_DEV_PULS_OXIM_SAT_O2_CHAN");
const std::string DIMENSION_PERCENTAGE("MDC_DIM_PERCENT");
const std::string DIMENSION_BEATS_PER_MIN("MDC_DIM_BEAT_PER_MIN");
const std::string PULSE_OXIMETER_SAT_O2_GET_HANDLE("MDC_PULS_OXIM_SAT_O2");
const std::string PULSE_OXIMETER_PULSE_RATE_GET_HANDLE("MDC_PULS_OXIM_PULS_RATE");
const std::string PULSE_OXIMETER_BATTERY_HANDLE("MDC_DEV_PULS_OXIM_BAT");
const std::string PULSE_OXIMETER_ALERT_SYSTEM_HANDLE("MDC_DEV_PULSE_OXIMETER_AL");
const std::string PULSE_OXIMETER_PULSE_RATE_LIMIT_ALERT_HANDLE("MDC_DEV_PULS_OXIM_PULS_AL_LIMIT_STAT");
const std::string PULSE_OXIMETER_SAT_O2_LIMIT_ALERT_HANDLE("MDC_DEV_PULS_OXIM_SAT_O2_AL_LIMIT_STAT");
const std::string PULSE_OXIMETER_PULSE_RATE_LIMIT_ALERT_SIGNAL_HANDLE("MDC_DEV_PULSE_OXIM_PULS_AL_LIMIT_SIGN");
const std::string PULSE_OXIMETER_SAT_O2_LIMIT_ALERT_SIGNAL_HANDLE("MDC_DEV_PULSE_OXIM_SAT_O2_AL_LIMIT_SIGN");


#endif /* CTESTCASES_TOOLS_PULSEOXIMETERHANDLENAMES_H_ */
