/*
 * Defaults.h
 *
 *  Created on: 20.07.2017
 *      Author: buerger
 *
 *  This file is autogenerated.
 *
 *  Do not edit this file. For customization please edit the Defaults_beginning.h or Defaults_ending.h
 */

#ifndef DATA_OSCP_MDIB_DEFAULTS_H_
#define DATA_OSCP_MDIB_DEFAULTS_H_

#include "OSCLib/Data/SDC/MDIB/MDIB-fwd.h"
#include "osdm-fwd.hxx"

namespace SDCLib {
namespace Data {
namespace SDC {

extern const std::string NOT_ASSIGNED;

class Defaults {
public:
	Defaults();
	virtual ~Defaults();
