/*
 * Defaults.h
 *
 *  Created on: 20.07.2017
 *      Author: buerger
 *
 *  This file is autogenerated.
 *
 *  Do not edit this file. For customization please edit the Defaults_beginning.h or Defaults_ending.h
 */

#include "OSCLib/Data/SDC/MDIB/Defaults.h"
#include "Poco/UUIDGenerator.h"
#include "OSCLib/Data/SDC/MDIB/SimpleTypesMapping.h"
#include "OSCLib/Data/SDC/MDIB/ConvertFromCDM.h"
#include "OSCLib/Data/SDC/MDIB/ConvertToCDM.h"

#include "osdm.hxx"

namespace OSCLib {
namespace Data {
namespace SDC {

const std::string NOT_ASSIGNED("Invalid. Not assigned!");

Defaults::Defaults() {

}

Defaults::~Defaults() {

}


