/*
 * MDIB-fwd.h
 *
 *  Created on: 28.06.2017
 *      Author: buerger
 *
 *  This file is autogenerated.
 *
 *  It contains the forward declarations for all complex datatypes from the datamodel and messagemodel.
 *
 *  Do not edit this file. For customization please edit the MDIB-fwd_beginning.hxx or MDIB-fwd_ending.hxx
 */

#ifndef OSCLIB_DATA_OSCP_MDIB_MDIB_FWD_H_
#define OSCLIB_DATA_OSCP_MDIB_MDIB_FWD_H_

namespace SDCLib {
namespace Data {
namespace SDC {
	// classes, that are implemented manually
	class MdibContainer;
	class OperationInvocationContext;

	// classes, that are generated
