/*
 * SimpleTypesMapping.cpp
 *
 *  Created on: 22.06.2017
 *      Author: buerger
 *
 *  This file is autogenerated.
 *
 *  Do not edit this file. For customization please edit the SimpleTypesMapping_beginning.cxx or SimpleTypesMapping_ending.cxx
 */


#include "SDCLib/Data/SDC/MDIB/SimpleTypesMapping.h"
#include "osdm.hxx"

#include <stdexcept>

namespace SDCLib {
namespace Data {
namespace SDC {

EnumToString::EnumToString() {

}

EnumToString::~EnumToString() {

}
