/*
 * SimpleTypesMapping.h
 *
 *  Created on: 22.06.2017
 *      Author: buerger
 *
 *  This file is autogenerated.
 *
 *  Do not edit this file. For customization please edit the SimpleTypesMapping_beginning.hxx or SimpleTypesMapping_ending.hxx
 */

#ifndef SIMPLETYPESMAPPING_H_
#define SIMPLETYPESMAPPING_H_

#include "osdm-fwd.hxx"

namespace OSCLib {
namespace Data {
namespace OSCP {

