/*
 * Defaults.h
 *
 *  Created on: 20.07.2017
 *      Author: buerger
 *
 *  This file is autogenerated.
 *
 *  Do not edit this file. For customization please edit the Defaults_beginning.h or Defaults_ending.h
 */



#include "OSCLib/Data/OSCP/MDIB/Mdib.h"
#include "OSCLib/Data/OSCP/MDIB/MdDescription.h"
#include "OSCLib/Data/OSCP/MDIB/MdState.h"
#include "OSCLib/Data/OSCP/MDIB/LocalizedText.h"
#include "OSCLib/Data/OSCP/MDIB/CodedValue.h"
#include "OSCLib/Data/OSCP/MDIB/InstanceIdentifier.h"
#include "OSCLib/Data/OSCP/MDIB/Range.h"
#include "OSCLib/Data/OSCP/MDIB/Measurement.h"
#include "OSCLib/Data/OSCP/MDIB/ApprovedJurisdictions.h"
#include "OSCLib/Data/OSCP/MDIB/OperatingJurisdiction.h"
#include "OSCLib/Data/OSCP/MDIB/ProductionSpecification.h"
#include "OSCLib/Data/OSCP/MDIB/CalibrationInfo.h"
#include "OSCLib/Data/OSCP/MDIB/MdsDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/MetaData.h"
#include "OSCLib/Data/OSCP/MDIB/Udi.h"
#include "OSCLib/Data/OSCP/MDIB/MdsState.h"
#include "OSCLib/Data/OSCP/MDIB/VmdDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/VmdState.h"
#include "OSCLib/Data/OSCP/MDIB/ChannelDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/ChannelState.h"
#include "OSCLib/Data/OSCP/MDIB/SystemSignalActivation.h"
#include "OSCLib/Data/OSCP/MDIB/AlertSystemDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/AlertSystemState.h"
#include "OSCLib/Data/OSCP/MDIB/CauseInfo.h"
#include "OSCLib/Data/OSCP/MDIB/RemedyInfo.h"
#include "OSCLib/Data/OSCP/MDIB/AlertConditionDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/AlertConditionState.h"
#include "OSCLib/Data/OSCP/MDIB/LimitAlertConditionDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/LimitAlertConditionState.h"
#include "OSCLib/Data/OSCP/MDIB/AlertSignalDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/AlertSignalState.h"
#include "OSCLib/Data/OSCP/MDIB/MetricQuality.h"
#include "OSCLib/Data/OSCP/MDIB/Annotation.h"
#include "OSCLib/Data/OSCP/MDIB/NumericMetricValue.h"
#include "OSCLib/Data/OSCP/MDIB/StringMetricValue.h"
#include "OSCLib/Data/OSCP/MDIB/SampleArrayValue.h"
#include "OSCLib/Data/OSCP/MDIB/ApplyAnnotation.h"
#include "OSCLib/Data/OSCP/MDIB/Relation.h"
#include "OSCLib/Data/OSCP/MDIB/NumericMetricDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/NumericMetricState.h"
#include "OSCLib/Data/OSCP/MDIB/StringMetricDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/StringMetricState.h"
#include "OSCLib/Data/OSCP/MDIB/EnumStringMetricDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/AllowedValue.h"
#include "OSCLib/Data/OSCP/MDIB/EnumStringMetricState.h"
#include "OSCLib/Data/OSCP/MDIB/RealTimeSampleArrayMetricDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/RealTimeSampleArrayMetricState.h"
#include "OSCLib/Data/OSCP/MDIB/DistributionSampleArrayMetricDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/DistributionSampleArrayMetricState.h"
#include "OSCLib/Data/OSCP/MDIB/ScoDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/ScoState.h"
#include "OSCLib/Data/OSCP/MDIB/SetValueOperationDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/SetValueOperationState.h"
#include "OSCLib/Data/OSCP/MDIB/SetStringOperationDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/SetStringOperationState.h"
#include "OSCLib/Data/OSCP/MDIB/AllowedValues.h"
#include "OSCLib/Data/OSCP/MDIB/ActivateOperationDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/Argument.h"
#include "OSCLib/Data/OSCP/MDIB/ActivateOperationState.h"
#include "OSCLib/Data/OSCP/MDIB/SetContextStateOperationDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/SetContextStateOperationState.h"
#include "OSCLib/Data/OSCP/MDIB/SetMetricStateOperationDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/SetMetricStateOperationState.h"
#include "OSCLib/Data/OSCP/MDIB/SetComponentStateOperationDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/SetComponentStateOperationState.h"
#include "OSCLib/Data/OSCP/MDIB/SetAlertStateOperationDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/SetAlertStateOperationState.h"
#include "OSCLib/Data/OSCP/MDIB/ClockDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/ClockState.h"
#include "OSCLib/Data/OSCP/MDIB/BatteryDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/BatteryState.h"
#include "OSCLib/Data/OSCP/MDIB/SystemContextDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/SystemContextState.h"
#include "OSCLib/Data/OSCP/MDIB/BaseDemographics.h"
#include "OSCLib/Data/OSCP/MDIB/PersonReference.h"
#include "OSCLib/Data/OSCP/MDIB/LocationDetail.h"
#include "OSCLib/Data/OSCP/MDIB/PatientContextDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/PatientDemographicsCoreData.h"
#include "OSCLib/Data/OSCP/MDIB/NeonatalPatientDemographicsCoreData.h"
#include "OSCLib/Data/OSCP/MDIB/PatientContextState.h"
#include "OSCLib/Data/OSCP/MDIB/LocationContextDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/LocationContextState.h"
#include "OSCLib/Data/OSCP/MDIB/WorkflowContextDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/ClinicalInfo.h"
#include "OSCLib/Data/OSCP/MDIB/RelatedMeasurement.h"
#include "OSCLib/Data/OSCP/MDIB/ReferenceRange.h"
#include "OSCLib/Data/OSCP/MDIB/ImagingProcedure.h"
#include "OSCLib/Data/OSCP/MDIB/LocationReference.h"
#include "OSCLib/Data/OSCP/MDIB/OrderDetail.h"
#include "OSCLib/Data/OSCP/MDIB/PersonParticipation.h"
#include "OSCLib/Data/OSCP/MDIB/WorkflowContextState.h"
#include "OSCLib/Data/OSCP/MDIB/WorkflowDetail.h"
#include "OSCLib/Data/OSCP/MDIB/RequestedOrderDetail.h"
#include "OSCLib/Data/OSCP/MDIB/PerformedOrderDetail.h"
#include "OSCLib/Data/OSCP/MDIB/OperatorContextDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/OperatorContextState.h"
#include "OSCLib/Data/OSCP/MDIB/MeansContextDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/MeansContextState.h"
#include "OSCLib/Data/OSCP/MDIB/EnsembleContextDescriptor.h"
#include "OSCLib/Data/OSCP/MDIB/EnsembleContextState.h"
#include "OSCLib/Data/OSCP/MDIB/ContainmentTree.h"
#include "OSCLib/Data/OSCP/MDIB/ContainmentTreeEntry.h"
#include "OSCLib/Data/OSCP/MDIB/DicomTransferCapability.h"
#include "OSCLib/Data/OSCP/MDIB/DicomNetworkAe.h"
#include "OSCLib/Data/OSCP/MDIB/DicomNetworkConnection.h"
#include "OSCLib/Data/OSCP/MDIB/DicomDeviceDescriptor.h"


#include "OSCLib/Data/OSCP/MDIB/Defaults.h"
#include "Poco/UUIDGenerator.h"
#include "OSCLib/Data/OSCP/MDIB/SimpleTypesMapping.h"
#include "OSCLib/Data/OSCP/MDIB/ConvertFromCDM.h"
#include "OSCLib/Data/OSCP/MDIB/ConvertToCDM.h"

#include "osdm.hxx"

namespace OSCLib {
namespace Data {
namespace OSCP {

const std::string NOT_ASSIGNED("Invalid. Not assigned!");

Defaults::Defaults() {

}

Defaults::~Defaults() {

}



CDM::Mdib  * Defaults::Mdib() {
	return new CDM::Mdib(NOT_ASSIGNED);
}

CDM::MdDescription  * Defaults::MdDescription() {
	return new CDM::MdDescription();
}

CDM::MdState  * Defaults::MdState() {
	return new CDM::MdState();
}

CDM::LocalizedText  * Defaults::LocalizedText() {
	return new CDM::LocalizedText(NOT_ASSIGNED);
}

CDM::CodedValue  * Defaults::CodedValue() {
	return new CDM::CodedValue(NOT_ASSIGNED);
}

CDM::InstanceIdentifier  * Defaults::InstanceIdentifier() {
	return new CDM::InstanceIdentifier();
}

CDM::Range  * Defaults::Range() {
	return new CDM::Range();
}

CDM::Measurement  * Defaults::Measurement() {
	return new CDM::Measurement(ConvertToCDM::convert(OSCP::CodedValue()),
			0);
}

CDM::ApprovedJurisdictions  * Defaults::ApprovedJurisdictions() {
	return new CDM::ApprovedJurisdictions();
}

CDM::OperatingJurisdiction  * Defaults::OperatingJurisdiction() {
	return new CDM::OperatingJurisdiction();
}

CDM::ProductionSpecification  * Defaults::ProductionSpecification() {
	return new CDM::ProductionSpecification(ConvertToCDM::convert(OSCP::CodedValue()),
			"not assigned");
}

CDM::CalibrationInfo  * Defaults::CalibrationInfo() {
	return new CDM::CalibrationInfo();
}

CDM::MdsDescriptor  * Defaults::MdsDescriptor() {
	return new CDM::MdsDescriptor(NOT_ASSIGNED);
}

CDM::MetaData  * Defaults::MetaData() {
	return new CDM::MetaData();
}

CDM::Udi  * Defaults::Udi() {
	return new CDM::Udi(NOT_ASSIGNED,
			NOT_ASSIGNED,
			ConvertToCDM::convert(OSCP::InstanceIdentifier()));
}

CDM::MdsState  * Defaults::MdsState() {
	return new CDM::MdsState(NOT_ASSIGNED);
}

CDM::VmdDescriptor  * Defaults::VmdDescriptor() {
	return new CDM::VmdDescriptor(NOT_ASSIGNED);
}

CDM::VmdState  * Defaults::VmdState() {
	return new CDM::VmdState(NOT_ASSIGNED);
}

CDM::ChannelDescriptor  * Defaults::ChannelDescriptor() {
	return new CDM::ChannelDescriptor(NOT_ASSIGNED);
}

CDM::ChannelState  * Defaults::ChannelState() {
	return new CDM::ChannelState(NOT_ASSIGNED);
}

CDM::SystemSignalActivation  * Defaults::SystemSignalActivation() {
	return new CDM::SystemSignalActivation(NOT_ASSIGNED,
			CDM::AlertActivation::Off);
}

CDM::AlertSystemDescriptor  * Defaults::AlertSystemDescriptor() {
	return new CDM::AlertSystemDescriptor(NOT_ASSIGNED);
}

CDM::AlertSystemState  * Defaults::AlertSystemState() {
	return new CDM::AlertSystemState(NOT_ASSIGNED,
			CDM::AlertActivation::Off);
}

CDM::CauseInfo  * Defaults::CauseInfo() {
	return new CDM::CauseInfo();
}

CDM::RemedyInfo  * Defaults::RemedyInfo() {
	return new CDM::RemedyInfo();
}

CDM::AlertConditionDescriptor  * Defaults::AlertConditionDescriptor() {
	return new CDM::AlertConditionDescriptor(NOT_ASSIGNED,
			CDM::AlertConditionKind::Oth,
			NOT_ASSIGNED);
}

CDM::AlertConditionState  * Defaults::AlertConditionState() {
	return new CDM::AlertConditionState(NOT_ASSIGNED,
			CDM::AlertActivation::Off);
}

CDM::LimitAlertConditionDescriptor  * Defaults::LimitAlertConditionDescriptor() {
	CDM::LimitAlertConditionDescriptor::HandleType ht = NOT_ASSIGNED;

	return new CDM::LimitAlertConditionDescriptor(NOT_ASSIGNED,
			CDM::LimitAlertConditionDescriptor::KindType::Oth,
			CDM::LimitAlertConditionDescriptor::PriorityType::None,
			ConvertToCDM::convert(OSCP::Range()));
}

CDM::LimitAlertConditionState  * Defaults::LimitAlertConditionState() {
	return new CDM::LimitAlertConditionState(NOT_ASSIGNED,
			CDM::LimitAlertConditionState::ActivationStateType::Off,
			ConvertToCDM::convert(OSCP::Range()),
			CDM::LimitAlertConditionState::MonitoredAlertLimitsType::All);
}

CDM::AlertSignalDescriptor  * Defaults::AlertSignalDescriptor() {
	return new CDM::AlertSignalDescriptor(NOT_ASSIGNED,
			CDM::AlertSignalManifestation::Oth,
			false);
}

CDM::AlertSignalState  * Defaults::AlertSignalState() {
	return new CDM::AlertSignalState(NOT_ASSIGNED,
			CDM::AlertActivation::Off);
}

CDM::MetricQuality  * Defaults::MetricQuality() {
	return new CDM::MetricQuality(CDM::MeasurementValidity::NA);
}

CDM::Annotation  * Defaults::Annotation() {
	return new CDM::Annotation(ConvertToCDM::convert(OSCP::CodedValue()));
}

CDM::NumericMetricValue  * Defaults::NumericMetricValue() {
	return new CDM::NumericMetricValue(ConvertToCDM::convert(OSCP::MetricQuality()));
}

CDM::StringMetricValue  * Defaults::StringMetricValue() {
	return new CDM::StringMetricValue(ConvertToCDM::convert(OSCP::MetricQuality()));
}

CDM::SampleArrayValue  * Defaults::SampleArrayValue() {
	return new CDM::SampleArrayValue(ConvertToCDM::convert(OSCP::MetricQuality()));
}

CDM::ApplyAnnotation  * Defaults::ApplyAnnotation() {
	return new CDM::ApplyAnnotation(0,
			0);
}

CDM::Relation  * Defaults::Relation() {
	return new CDM::Relation(CDM::Kind::Oth,
			NOT_ASSIGNED);
}

CDM::NumericMetricDescriptor  * Defaults::NumericMetricDescriptor() {
	return new CDM::NumericMetricDescriptor(NOT_ASSIGNED,
			ConvertToCDM::convert(OSCP::CodedValue()),
			CDM::MetricCategory::Unspec,
			CDM::MetricAvailability::Cont,
			xml_schema::Decimal(0.0000001));
}

CDM::NumericMetricState  * Defaults::NumericMetricState() {
	return new CDM::NumericMetricState(NOT_ASSIGNED);
}

CDM::StringMetricDescriptor  * Defaults::StringMetricDescriptor() {
	return new CDM::StringMetricDescriptor(NOT_ASSIGNED,
			ConvertToCDM::convert(OSCP::CodedValue()),
			CDM::MetricCategory::Unspec,
			CDM::MetricAvailability::Cont);
}

CDM::StringMetricState  * Defaults::StringMetricState() {
	return new CDM::StringMetricState(NOT_ASSIGNED);
}

CDM::EnumStringMetricDescriptor  * Defaults::EnumStringMetricDescriptor() {
	return new CDM::EnumStringMetricDescriptor(NOT_ASSIGNED,
			ConvertToCDM::convert(OSCP::CodedValue()),
			CDM::MetricCategory::Unspec,
			CDM::MetricAvailability::Cont);
}

CDM::AllowedValue  * Defaults::AllowedValue() {
	return new CDM::AllowedValue(NOT_ASSIGNED);
}

CDM::EnumStringMetricState  * Defaults::EnumStringMetricState() {
	return new CDM::EnumStringMetricState(NOT_ASSIGNED);
}

CDM::RealTimeSampleArrayMetricDescriptor  * Defaults::RealTimeSampleArrayMetricDescriptor() {
	return new CDM::RealTimeSampleArrayMetricDescriptor(NOT_ASSIGNED,
			ConvertToCDM::convert(OSCP::CodedValue()),
			CDM::MetricCategory::Unspec,
			CDM::MetricAvailability::Cont,
			xml_schema::Decimal(1),
			xml_schema::Duration(false,0,0,0,0,0,1));
}

CDM::RealTimeSampleArrayMetricState  * Defaults::RealTimeSampleArrayMetricState() {
	return new CDM::RealTimeSampleArrayMetricState(NOT_ASSIGNED);
}

CDM::DistributionSampleArrayMetricDescriptor  * Defaults::DistributionSampleArrayMetricDescriptor() {
	return new CDM::DistributionSampleArrayMetricDescriptor(NOT_ASSIGNED,
			ConvertToCDM::convert(OSCP::CodedValue()),
			CDM::MetricCategory::Unspec,
			CDM::MetricAvailability::Cont,
			ConvertToCDM::convert(OSCP::CodedValue()),
			ConvertToCDM::convert(OSCP::Range()),
			xml_schema::Decimal(1));
}

CDM::DistributionSampleArrayMetricState  * Defaults::DistributionSampleArrayMetricState() {
	return new CDM::DistributionSampleArrayMetricState(NOT_ASSIGNED);
}

CDM::ScoDescriptor  * Defaults::ScoDescriptor() {
	return new CDM::ScoDescriptor(NOT_ASSIGNED);
}

CDM::ScoState  * Defaults::ScoState() {
	return new CDM::ScoState(NOT_ASSIGNED);
}

CDM::SetValueOperationDescriptor  * Defaults::SetValueOperationDescriptor() {
	return new CDM::SetValueOperationDescriptor(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::SetValueOperationState  * Defaults::SetValueOperationState() {
	return new CDM::SetValueOperationState(NOT_ASSIGNED,
			CDM::OperatingMode::NA);
}

CDM::SetStringOperationDescriptor  * Defaults::SetStringOperationDescriptor() {
	return new CDM::SetStringOperationDescriptor(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::SetStringOperationState  * Defaults::SetStringOperationState() {
	return new CDM::SetStringOperationState(NOT_ASSIGNED,
			CDM::OperatingMode::NA);
}

CDM::AllowedValues  * Defaults::AllowedValues() {
	return new CDM::AllowedValues(NOT_ASSIGNED);
}

CDM::ActivateOperationDescriptor  * Defaults::ActivateOperationDescriptor() {
	return new CDM::ActivateOperationDescriptor(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::Argument  * Defaults::Argument() {
	return new CDM::Argument(ConvertToCDM::convert(OSCP::CodedValue()),
			xml_schema::Qname(NOT_ASSIGNED));
}

CDM::ActivateOperationState  * Defaults::ActivateOperationState() {
	return new CDM::ActivateOperationState(NOT_ASSIGNED,
			CDM::OperatingMode::NA);
}

CDM::SetContextStateOperationDescriptor  * Defaults::SetContextStateOperationDescriptor() {
	return new CDM::SetContextStateOperationDescriptor(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::SetContextStateOperationState  * Defaults::SetContextStateOperationState() {
	return new CDM::SetContextStateOperationState(NOT_ASSIGNED,
			CDM::OperatingMode::NA);
}

CDM::SetMetricStateOperationDescriptor  * Defaults::SetMetricStateOperationDescriptor() {
	return new CDM::SetMetricStateOperationDescriptor(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::SetMetricStateOperationState  * Defaults::SetMetricStateOperationState() {
	return new CDM::SetMetricStateOperationState(NOT_ASSIGNED,
			CDM::OperatingMode::NA);
}

CDM::SetComponentStateOperationDescriptor  * Defaults::SetComponentStateOperationDescriptor() {
	return new CDM::SetComponentStateOperationDescriptor(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::SetComponentStateOperationState  * Defaults::SetComponentStateOperationState() {
	return new CDM::SetComponentStateOperationState(NOT_ASSIGNED,
			CDM::OperatingMode::NA);
}

CDM::SetAlertStateOperationDescriptor  * Defaults::SetAlertStateOperationDescriptor() {
	return new CDM::SetAlertStateOperationDescriptor(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::SetAlertStateOperationState  * Defaults::SetAlertStateOperationState() {
	return new CDM::SetAlertStateOperationState(NOT_ASSIGNED,
			CDM::OperatingMode::NA);
}

CDM::ClockDescriptor  * Defaults::ClockDescriptor() {
	return new CDM::ClockDescriptor(NOT_ASSIGNED);
}

CDM::ClockState  * Defaults::ClockState() {
	return new CDM::ClockState(NOT_ASSIGNED,
			false);
}

CDM::BatteryDescriptor  * Defaults::BatteryDescriptor() {
	return new CDM::BatteryDescriptor(NOT_ASSIGNED);
}

CDM::BatteryState  * Defaults::BatteryState() {
	return new CDM::BatteryState(NOT_ASSIGNED);
}

CDM::SystemContextDescriptor  * Defaults::SystemContextDescriptor() {
	return new CDM::SystemContextDescriptor(NOT_ASSIGNED);
}

CDM::SystemContextState  * Defaults::SystemContextState() {
	return new CDM::SystemContextState(NOT_ASSIGNED);
}

CDM::BaseDemographics  * Defaults::BaseDemographics() {
	return new CDM::BaseDemographics();
}

CDM::PersonReference  * Defaults::PersonReference() {
	return new CDM::PersonReference();
}

CDM::LocationDetail  * Defaults::LocationDetail() {
	return new CDM::LocationDetail();
}

CDM::PatientContextDescriptor  * Defaults::PatientContextDescriptor() {
	return new CDM::PatientContextDescriptor(NOT_ASSIGNED);
}

CDM::PatientDemographicsCoreData  * Defaults::PatientDemographicsCoreData() {
	return new CDM::PatientDemographicsCoreData();
}

CDM::NeonatalPatientDemographicsCoreData  * Defaults::NeonatalPatientDemographicsCoreData() {
	return new CDM::NeonatalPatientDemographicsCoreData();
}

CDM::PatientContextState  * Defaults::PatientContextState() {
	return new CDM::PatientContextState(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::LocationContextDescriptor  * Defaults::LocationContextDescriptor() {
	return new CDM::LocationContextDescriptor(NOT_ASSIGNED);
}

CDM::LocationContextState  * Defaults::LocationContextState() {
	return new CDM::LocationContextState(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::WorkflowContextDescriptor  * Defaults::WorkflowContextDescriptor() {
	return new CDM::WorkflowContextDescriptor(NOT_ASSIGNED);
}

CDM::ClinicalInfo  * Defaults::ClinicalInfo() {
	return new CDM::ClinicalInfo();
}

CDM::RelatedMeasurement  * Defaults::RelatedMeasurement() {
	return new CDM::RelatedMeasurement(ConvertToCDM::convert(OSCP::Measurement()));
}

CDM::ReferenceRange  * Defaults::ReferenceRange() {
	return new CDM::ReferenceRange(ConvertToCDM::convert(OSCP::Range()));
}

CDM::ImagingProcedure  * Defaults::ImagingProcedure() {
	return new CDM::ImagingProcedure(ConvertToCDM::convert(OSCP::InstanceIdentifier()),
			ConvertToCDM::convert(OSCP::InstanceIdentifier()),
			ConvertToCDM::convert(OSCP::InstanceIdentifier()),
			ConvertToCDM::convert(OSCP::InstanceIdentifier()));
}

CDM::LocationReference  * Defaults::LocationReference() {
	return new CDM::LocationReference();
}

CDM::OrderDetail  * Defaults::OrderDetail() {
	return new CDM::OrderDetail();
}

CDM::PersonParticipation  * Defaults::PersonParticipation() {
	return new CDM::PersonParticipation();
}

CDM::WorkflowContextState  * Defaults::WorkflowContextState() {
	return new CDM::WorkflowContextState(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::WorkflowDetail  * Defaults::WorkflowDetail() {
	return new CDM::WorkflowDetail(ConvertToCDM::convert(OSCP::PersonReference()));
}

CDM::RequestedOrderDetail  * Defaults::RequestedOrderDetail() {
	return new CDM::RequestedOrderDetail(ConvertToCDM::convert(OSCP::InstanceIdentifier()));
}

CDM::PerformedOrderDetail  * Defaults::PerformedOrderDetail() {
	return new CDM::PerformedOrderDetail();
}

CDM::OperatorContextDescriptor  * Defaults::OperatorContextDescriptor() {
	return new CDM::OperatorContextDescriptor(NOT_ASSIGNED);
}

CDM::OperatorContextState  * Defaults::OperatorContextState() {
	return new CDM::OperatorContextState(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::MeansContextDescriptor  * Defaults::MeansContextDescriptor() {
	return new CDM::MeansContextDescriptor(NOT_ASSIGNED);
}

CDM::MeansContextState  * Defaults::MeansContextState() {
	return new CDM::MeansContextState(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::EnsembleContextDescriptor  * Defaults::EnsembleContextDescriptor() {
	return new CDM::EnsembleContextDescriptor(NOT_ASSIGNED);
}

CDM::EnsembleContextState  * Defaults::EnsembleContextState() {
	return new CDM::EnsembleContextState(NOT_ASSIGNED,
			NOT_ASSIGNED);
}

CDM::ContainmentTree  * Defaults::ContainmentTree() {
	return new CDM::ContainmentTree();
}

CDM::ContainmentTreeEntry  * Defaults::ContainmentTreeEntry() {
	return new CDM::ContainmentTreeEntry();
}


CDM::DicomTransferCapability  * Defaults::DicomTransferCapability() {
	// randomly chosen: Scu = client. Adapt to custom needs!
	return new CDM::DicomTransferCapability(NOT_ASSIGNED,
			CDM::DicomTransferRole::Scu);
}

CDM::DicomNetworkAe  * Defaults::DicomNetworkAe() {
	return new CDM::DicomNetworkAe(NOT_ASSIGNED,
			CDM::DicomNetworkAe::NetworkConnectionReferenceType(),
			false,
			false);
}

CDM::DicomNetworkConnection  * Defaults::DicomNetworkConnection() {
	return new CDM::DicomNetworkConnection(xml_schema::Id(NOT_ASSIGNED),
			NOT_ASSIGNED);
}

CDM::DicomDeviceDescriptor  * Defaults::DicomDeviceDescriptor() {
	return new CDM::DicomDeviceDescriptor(NOT_ASSIGNED);
}

// new D10
CDM::CalibrationResult * Defaults::CalibrationResult() {
	return new CDM::CalibrationResult(ConvertToCDM::convert(OSCP::CodedValue()),
			ConvertToCDM::convert(OSCP::Measurement()));
}


CDM::CalibrationDocumentation * Defaults::CalibrationDocumentation() {
	return new CDM::CalibrationDocumentation();
}

CDM::Translation * Defaults::Translation() {
	return new CDM::Translation(NOT_ASSIGNED);
}

CDM::OperationGroup * Defaults::OperationGroup() {
	return new CDM::OperationGroup(ConvertToCDM::convert(OSCP::CodedValue()));
}

CDM::PhysicalConnectorInfo * Defaults::PhysicalConnectorInfo() {
	return new CDM::PhysicalConnectorInfo();
}


} /* namespace OSCP */
} /* namespace Data */
} /* namespace OSCLib */
