/*
 * ConvertFromCDM.h
 *
 *  Created on: 22.06.2017
 *      Author: buerger
 *
 *  This file is autogenerated.
 *
 *  Do not edit this file. For customization please edit the ConvertFromCDM_beginning.hxx or ConvertFromCDM_ending.hxx
 */

#ifndef DATA_OSCP_MDIB_CONVERTFROMCDM_H_
#define DATA_OSCP_MDIB_CONVERTFROMCDM_H_

#include "OSCLib/Data/OSCP/MDIB/SimpleTypesMapping.h"
#include "OSCLib/Data/OSCP/MDIB/MDIB-fwd.h"
#include "osdm-fwd.hxx"

namespace OSCLib {
namespace Data {
namespace OSCP {

class ConvertFromCDM {
public:
	ConvertFromCDM();
	virtual ~ConvertFromCDM();

	// autogenerated here
	static MeasurementValidity convert(const CDM::MeasurementValidity & source);
	static SafetyClassification convert(const CDM::SafetyClassification & source);
	static ComponentActivation convert(const CDM::ComponentActivation & source);
	static CalibrationState convert(const CDM::CalibrationState & source);
	static CalibrationType convert(const CDM::CalibrationType & source);
	static MdsOperatingMode convert(const CDM::MdsOperatingMode & source);
	static AlertActivation convert(const CDM::AlertActivation & source);
	static AlertConditionKind convert(const CDM::AlertConditionKind & source);
	static AlertConditionPriority convert(const CDM::AlertConditionPriority & source);
	static AlertConditionReference convert(const CDM::AlertConditionReference & source);
	static AlertConditionMonitoredLimits convert(const CDM::AlertConditionMonitoredLimits & source);
	static AlertSignalManifestation convert(const CDM::AlertSignalManifestation & source);
	static AlertSignalPresence convert(const CDM::AlertSignalPresence & source);
	static AlertSignalPrimaryLocation convert(const CDM::AlertSignalPrimaryLocation & source);
	static GenerationMode convert(const CDM::GenerationMode & source);
	static RealTimeValueType convert(const CDM::RealTimeValueType & source);
	static MetricCategory convert(const CDM::MetricCategory & source);
	static DerivationMethod convert(const CDM::DerivationMethod & source);
	static MetricAvailability convert(const CDM::MetricAvailability & source);
	static OperatingMode convert(const CDM::OperatingMode & source);
	static ContextAssociation convert(const CDM::ContextAssociation & source);
	static Sex convert(const CDM::Sex & source);
	static PatientType convert(const CDM::PatientType & source);
	static Mdib convert(const CDM::Mdib & source);
	static MdDescription convert(const CDM::MdDescription & source);
	static MdState convert(const CDM::MdState & source);
	static LocalizedText convert(const CDM::LocalizedText & source);
	static CodedValue convert(const CDM::CodedValue & source);
	static InstanceIdentifier convert(const CDM::InstanceIdentifier & source);
	static Range convert(const CDM::Range & source);
	static Measurement convert(const CDM::Measurement & source);
	static AbstractDescriptor convert(const CDM::AbstractDescriptor & source);
	static AbstractState convert(const CDM::AbstractState & source);
	static AbstractMultiState convert(const CDM::AbstractMultiState & source);
	static AbstractDeviceComponentDescriptor convert(const CDM::AbstractDeviceComponentDescriptor & source);
	static ProductionSpecificationType convert(const CDM::ProductionSpecificationType & source);
	static AbstractAlertingDeviceComponentDescriptor convert(const CDM::AbstractAlertingDeviceComponentDescriptor & source);
	static CalibrationInfo convert(const CDM::CalibrationInfo & source);
	static AbstractDeviceComponentState convert(const CDM::AbstractDeviceComponentState & source);
	static AbstractAlertingDeviceComponentState convert(const CDM::AbstractAlertingDeviceComponentState & source);
	static MdsDescriptor convert(const CDM::MdsDescriptor & source);
	static MetaDataType convert(const CDM::MetaDataType & source);
	static MdsState convert(const CDM::MdsState & source);
	static VmdDescriptor convert(const CDM::VmdDescriptor & source);
	static VmdState convert(const CDM::VmdState & source);
	static ChannelDescriptor convert(const CDM::ChannelDescriptor & source);
	static ChannelState convert(const CDM::ChannelState & source);
	static AbstractAlertDescriptor convert(const CDM::AbstractAlertDescriptor & source);
	static AbstractAlertState convert(const CDM::AbstractAlertState & source);
	static SystemSignalActivation convert(const CDM::SystemSignalActivation & source);
	static AlertSystemDescriptor convert(const CDM::AlertSystemDescriptor & source);
	static AlertSystemState convert(const CDM::AlertSystemState & source);
	static CauseInfo convert(const CDM::CauseInfo & source);
	static RemedyInfo convert(const CDM::RemedyInfo & source);
	static AlertConditionDescriptor convert(const CDM::AlertConditionDescriptor & source);
	static AlertConditionState convert(const CDM::AlertConditionState & source);
	static LimitAlertConditionDescriptor convert(const CDM::LimitAlertConditionDescriptor & source);
	static LimitAlertConditionState convert(const CDM::LimitAlertConditionState & source);
	static AlertSignalDescriptor convert(const CDM::AlertSignalDescriptor & source);
	static AlertSignalState convert(const CDM::AlertSignalState & source);
	static AbstractMetricValue convert(const CDM::AbstractMetricValue & source);
	static MetricQualityType convert(const CDM::MetricQualityType & source);
	static AnnotationType convert(const CDM::AnnotationType & source);
	static NumericMetricValue convert(const CDM::NumericMetricValue & source);
	static StringMetricValue convert(const CDM::StringMetricValue & source);
	static SampleArrayValue convert(const CDM::SampleArrayValue & source);
	static ApplyAnnotationType convert(const CDM::ApplyAnnotationType & source);
	static AbstractMetricDescriptor convert(const CDM::AbstractMetricDescriptor & source);
	static AbstractMetricState convert(const CDM::AbstractMetricState & source);
	static NumericMetricDescriptor convert(const CDM::NumericMetricDescriptor & source);
	static NumericMetricState convert(const CDM::NumericMetricState & source);
	static StringMetricDescriptor convert(const CDM::StringMetricDescriptor & source);
	static StringMetricState convert(const CDM::StringMetricState & source);
	static EnumStringMetricDescriptor convert(const CDM::EnumStringMetricDescriptor & source);
	static AllowedValueType convert(const CDM::AllowedValueType & source);
	static EnumStringMetricState convert(const CDM::EnumStringMetricState & source);
	static RealTimeSampleArrayMetricDescriptor convert(const CDM::RealTimeSampleArrayMetricDescriptor & source);
	static RealTimeSampleArrayMetricState convert(const CDM::RealTimeSampleArrayMetricState & source);
	static DistributionSampleArrayMetricDescriptor convert(const CDM::DistributionSampleArrayMetricDescriptor & source);
	static DistributionSampleArrayMetricState convert(const CDM::DistributionSampleArrayMetricState & source);
	static ScoDescriptor convert(const CDM::ScoDescriptor & source);
	static ScoState convert(const CDM::ScoState & source);
	static AbstractOperationDescriptor convert(const CDM::AbstractOperationDescriptor & source);
	static AbstractSetStateOperationDescriptor convert(const CDM::AbstractSetStateOperationDescriptor & source);
	static AbstractOperationState convert(const CDM::AbstractOperationState & source);
	static SetValueOperationDescriptor convert(const CDM::SetValueOperationDescriptor & source);
	static SetValueOperationState convert(const CDM::SetValueOperationState & source);
	static SetStringOperationDescriptor convert(const CDM::SetStringOperationDescriptor & source);
	static SetStringOperationState convert(const CDM::SetStringOperationState & source);
	static ActivateOperationDescriptor convert(const CDM::ActivateOperationDescriptor & source);
	static ArgumentType convert(const CDM::ArgumentType & source);
	static ActivateOperationState convert(const CDM::ActivateOperationState & source);
	static SetContextStateOperationDescriptor convert(const CDM::SetContextStateOperationDescriptor & source);
	static SetContextStateOperationState convert(const CDM::SetContextStateOperationState & source);
	static SetMetricStateOperationDescriptor convert(const CDM::SetMetricStateOperationDescriptor & source);
	static SetMetricStateOperationState convert(const CDM::SetMetricStateOperationState & source);
	static SetComponentStateOperationDescriptor convert(const CDM::SetComponentStateOperationDescriptor & source);
	static SetComponentStateOperationState convert(const CDM::SetComponentStateOperationState & source);
	static SetAlertStateOperationDescriptor convert(const CDM::SetAlertStateOperationDescriptor & source);
	static SetAlertStateOperationState convert(const CDM::SetAlertStateOperationState & source);
	static ClockDescriptor convert(const CDM::ClockDescriptor & source);
	static ClockState convert(const CDM::ClockState & source);
	static BatteryDescriptor convert(const CDM::BatteryDescriptor & source);
	static ChargeStatusType convert(const CDM::ChargeStatusType & source);
	static BatteryState convert(const CDM::BatteryState & source);
	static SystemContextDescriptor convert(const CDM::SystemContextDescriptor & source);
	static SystemContextState convert(const CDM::SystemContextState & source);
	static AbstractContextDescriptor convert(const CDM::AbstractContextDescriptor & source);
	static AbstractContextState convert(const CDM::AbstractContextState & source);
	static BaseDemographics convert(const CDM::BaseDemographics & source);
	static PersonReference convert(const CDM::PersonReference & source);
	static LocationDetail convert(const CDM::LocationDetail & source);
	static PatientContextDescriptor convert(const CDM::PatientContextDescriptor & source);
	static PatientDemographicsCoreData convert(const CDM::PatientDemographicsCoreData & source);
	static NeonatalPatientDemographicsCoreData convert(const CDM::NeonatalPatientDemographicsCoreData & source);
	static PatientContextState convert(const CDM::PatientContextState & source);
	static LocationContextDescriptor convert(const CDM::LocationContextDescriptor & source);
	static LocationContextState convert(const CDM::LocationContextState & source);
	static WorkflowContextDescriptor convert(const CDM::WorkflowContextDescriptor & source);
	static ClinicalInfo convert(const CDM::ClinicalInfo & source);
	static RelatedMeasurementType convert(const CDM::RelatedMeasurementType & source);
	static ReferenceRangeType convert(const CDM::ReferenceRangeType & source);
	static ImagingProcedure convert(const CDM::ImagingProcedure & source);
	static LocationReference convert(const CDM::LocationReference & source);
	static OrderDetail convert(const CDM::OrderDetail & source);
	static PersonParticipation convert(const CDM::PersonParticipation & source);
	static WorkflowContextState convert(const CDM::WorkflowContextState & source);
	static WorkflowDetailType convert(const CDM::WorkflowDetailType & source);
	static RequestedOrderDetailType convert(const CDM::RequestedOrderDetailType & source);
	static PerformedOrderDetailType convert(const CDM::PerformedOrderDetailType & source);
	static OperatorContextDescriptor convert(const CDM::OperatorContextDescriptor & source);
	static OperatorContextState convert(const CDM::OperatorContextState & source);
	static MeansContextDescriptor convert(const CDM::MeansContextDescriptor & source);
	static MeansContextState convert(const CDM::MeansContextState & source);
	static EnsembleContextDescriptor convert(const CDM::EnsembleContextDescriptor & source);
	static EnsembleContextState convert(const CDM::EnsembleContextState & source);
	static ContainmentTree convert(const CDM::ContainmentTree & source);
	static ContainmentTreeEntry convert(const CDM::ContainmentTreeEntry & source);
	static Timestamp convert(const Timestamp & source);
	static VersionCounter convert(const VersionCounter & source);
	static ReferencedVersion convert(const ReferencedVersion & source);
	static CodeIdentifier convert(const CodeIdentifier & source);
	static SymbolicCodeName convert(const SymbolicCodeName & source);
	static LocalizedTextRef convert(const LocalizedTextRef & source);
	static Handle convert(const Handle & source);
	static HandleRef convert(const HandleRef & source);
	static QualityIndicator convert(const QualityIndicator & source);
	static TimeZone convert(const TimeZone & source);
	static DateOfBirthType convert(const DateOfBirthType & source);
};

} /* namespace OSCP */
} /* namespace Data */
} /* namespace OSCLib */

#endif /* DATA_OSCP_MDIB_CONVERTFROMCDM_H_ */
